checker:
  # Amount of checks for a account many times to check a account.
  # Needs to be 1 or higher
  retries: 3

  # Higher for better accuracy but slower (counted in milliseconds)
  timeout: 15000

  # Threads for account checking
  threads: 100

  # Check hits if its a mail access
  mail_access: true
  
  # Save ranked accounts in secured.txt or unsecured.txt
  save_rankedtypes: true
  
  # Save bad accounts, good for checking paid alts (will use more cpu and take longer)
  save_bad: false

  # User should keep this false
  debugging: false
  
  # Api key to check hypixel ranks and levels
  # Get hypixel key by going to hypixel.net and do /api new
  # Free keys provided by Delta658 :D
  # 3217da80-0202-41a5-8399-df998a4425dd
  # 5549cdea-1378-4b00-b6a4-244b42846bde
  # 491cfe7f-e3e5-48b5-97ff-4b7d3e5fbe7f
  hypixel_api_key: '77de8865-1265-4496-9d79-f8cff96c4c86'

  capes:
    # Check capes
    liquidbounce: true
    optifine: true
    labymod:  true
    # Minecon/Mojang cape
    minecon:  true

  rank:
    mineplex: true
    hypixel:  true
    hivemc: true

  level:
    # Check Levels
    hypixel: true
    mineplex: true
    # Minimum high level accounts
    hypixel_level: 25
    mineplex_level: 25

  proxy:
    # If proxies should be used, Will be proxyless if set to false (Use VPN if set to false or you will be ip banned)
    proxy: true
    # Proxy types: https | socks4 | socks5
    proxy_type: 'https'
    # Proxy file name
    proxy_file: 'proxies.txt'
