checker:
  # Amount of checks for a account many times to check a account.
  # Needs to be 1 or higher
  retries: 3

  # Higher for better accuracy but slower (counted in milliseconds)
  timeout: 15000

  # Threads for account checking
  threads: 200

  # Save bad accounts, good for checking paid alts (will use more cpu and take longer)
  save_bad: false

  # User should keep this false
  debugging: false

  capes:
    # Check capes
    liquidbounce: true
    optifine: true
    labymod:  true
    # minecon capes
    minecon:  true

  rank:
    mineplex: true
    hypixel:  true
    hivemc: true

  level:
    # Check Levels
    hypixel: true
    mineplex: true
    # Minimum high level accounts
    hypixel_level: 25
    mineplex_level: 25

  proxy:
    # If proxies should be used, Will be proxyless if set to false (Use VPN if set to false or you will be ip banned)
    proxy: true
    # Proxy types: https | socks4 | socks5
    proxy_type: 'https'
    # Proxy file name
    proxy_file: 'proxies.txt'
